//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileConverter.FileConverterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileModel", Namespace="http://schemas.datacontract.org/2004/07/WcfFileConverter")]
    [System.SerializableAttribute()]
    public partial class FileModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileConverterService.IFileConverterService")]
    public interface IFileConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileConverterService/ConvertToCSV", ReplyAction="http://tempuri.org/IFileConverterService/ConvertToCSVResponse")]
        FileConverter.FileConverterService.FileModel ConvertToCSV(FileConverter.FileConverterService.FileModel file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileConverterService/ConvertToCSV", ReplyAction="http://tempuri.org/IFileConverterService/ConvertToCSVResponse")]
        System.Threading.Tasks.Task<FileConverter.FileConverterService.FileModel> ConvertToCSVAsync(FileConverter.FileConverterService.FileModel file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileConverterServiceChannel : FileConverter.FileConverterService.IFileConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileConverterServiceClient : System.ServiceModel.ClientBase<FileConverter.FileConverterService.IFileConverterService>, FileConverter.FileConverterService.IFileConverterService {
        
        public FileConverterServiceClient() {
        }
        
        public FileConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FileConverter.FileConverterService.FileModel ConvertToCSV(FileConverter.FileConverterService.FileModel file) {
            return base.Channel.ConvertToCSV(file);
        }
        
        public System.Threading.Tasks.Task<FileConverter.FileConverterService.FileModel> ConvertToCSVAsync(FileConverter.FileConverterService.FileModel file) {
            return base.Channel.ConvertToCSVAsync(file);
        }
    }
}
